<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>List user</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="http://chavel.me/api/assets/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="http://chavel.me/api/assets/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="http://chavel.me/api/assets/css/custom.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="http://chavel.me/api/assets/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>List users</h1>
                    <table class="table table-striped table-responsive ">
                        <tr>
                            <td>User id</td>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Image</td>
                            <td>Facebook ID</td>
                            <td>Phone</td>
                        </tr>
                        <?php foreach($data as $val){ ?>
                            <tr>
                                <td><?php echo $val['user_id']?></td>
                                <td><?php echo $val['user_name']?></td>
                                <td><?php echo $val['user_email']?></td>
                                <td><?php echo $val['user_image']?></td>
                                <td><?php echo $val['user_fb_id']?></td>
                                <td><?php echo $val['user_phone']?></td>
                            </tr>
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>
